services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
